name: PHPStan

on:
  - push
  - pull_request

jobs:
  phpcs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '7.4'
          - '8.0'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Install Dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}
      - name: Run PHPStan
        run: vendor/bin/phpstan --error-format github
